apiVersion: v1
king: Service
metadata:
    name: microservice-seguridad-service
    labels:
        name: microservice-seguridad-service
        app: microservice
spec:
 type: ClusterIp
 ports:
  - port: 80
    tagetPort: 80
 selector:
    app: microservice-seguridad
    type: microservice 