apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice
    name: microservice-libreria-deploy
  name: microservice-libreria-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-libreria
      type: microservice
  template:
    metadata:
      labels:
        app: microservice-libreria
        type: microservice
      name: microservice-libreria-pod
    spec:
      containers:
        - name: microservice-libreria-app
          image: camilocaste/serviciosapilibreria:latest
          ports:
            - containerPort: 80
          env:
            - name: MongoDb__ConnectionString
              value: "mongodb://camilo:$Camilo2025@mongo-service:27017"
